# Generated by Django 4.0.5 on 2022-06-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.CharField(max_length=100)),
                ('prob_desc', models.CharField(max_length=10000)),
                ('prob_diff', models.CharField(max_length=50)),
                ('solve_status', models.CharField(max_length=10)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=10000)),
                ('output', models.CharField(max_length=10000)),
                ('probId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestrap', models.DateTimeField(auto_now_add=True)),
                ('probId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.problem')),
            ],
        ),
    ]
