# Generated by Django 4.0.5 on 2022-07-08 03:22

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.FileField(default=True, upload_to=accounts.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])])),
                ('submitted_at', models.DateTimeField(verbose_name='Submitted on')),
                ('Verdict', models.CharField(blank=True, max_length=20, verbose_name='Verdict')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(max_length=200, upload_to='', verbose_name='Input')),
                ('output', models.CharField(max_length=200, verbose_name='Output')),
            ],
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='probId',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='prob_desc',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='prob_diff',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='prob_name',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='score',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solve_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.BigAutoField(db_column='Problem ID', default='0000000', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_level',
            field=models.CharField(db_column='Problem level', default='0000000', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(db_column='Problem Name', default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_statement',
            field=models.CharField(db_column='Problem Statement', default='0000000', max_length=400),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_status',
            field=models.BooleanField(db_column='Solve_status', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='0000000', max_length=30, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='sname',
            field=models.CharField(default='0000000', max_length=30, verbose_name='First Name'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.problem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.problem'),
        ),
    ]
