# Generated by Django 4.0.5 on 2022-07-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_solution_testcase_remove_test_cases_probid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
