# Generated by Django 4.0.5 on 2022-07-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_problem_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_level',
            field=models.CharField(db_column='Problem level', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(db_column='Problem Name', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_statement',
            field=models.CharField(db_column='Problem Statement', default='', max_length=400),
        ),
    ]
