# Generated by Django 4.0.5 on 2022-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_problem_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.BigAutoField(db_column='Problem ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_level',
            field=models.CharField(db_column='Problem level', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(db_column='Problem Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_statement',
            field=models.CharField(db_column='Problem Statement', max_length=400),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_status',
            field=models.BooleanField(db_column='Solve_status'),
        ),
    ]
